### ISSUE TITLE
Carousel view : is their any widget avalible in mdk

### ISSUE THREAD

**Issue by madhusinghandroid** [MovalysMDK/mdk-android-widget#1] opened 2016-07-27 06:25 UTC
Hi,

I have to implement carousel view, is their any widget defined for the same? If not is their any way to implement carousel view.

Thanks
Madhu Singh

**Comment by mlaffargue** [comment] 2016-07-27 07:23
Hi there's no carousel widget in the MDK. You can find different resources googling 'Android Carousel' as https://github.com/sayyam/carouselview for example.
The list of widgets available can be found in the doc : https://mdk.movalys.sopra.com/ under Resources > Docs > 6.4.2

Here are the current available widgets:

>    MDKCheckableImageButton
>    MDKCheckBox
>    MDKCommandButton
>    MDKDateTime
>    MDKCommandsEditText
>    MDKEditText
>    MDKEmail
>    MDKEmailView
>    MDKEnumView
>    MDKFixedList
>    MDKMapsPosition
>    MDKMedia
>    MDKPhone
>    MDKPosition
>    MDKPresenterView
>    MDKSeekBar
>    MDKSpinner
>    MDKStaticMapsPosition
>    MDKSwitch
>    MDKTintedTextView
>    MDKUri

**Comment by mlaffargue** [comment] 2016-07-27 07:23
Not a bug. Closing the thread.

**Closed as completed by mlaffargue** 2016-07-27 07:23 UTC
Labels: help wanted
